export type CanonicalMetricKey =
  | 'revenue'
  | 'gross_profit'
  | 'operating_income'
  | 'net_income'
  | 'assets'
  | 'liabilities'
  | 'equity'
  | 'cfo'
  | 'capex'
  | 'fcf'
  | 'shares';

export type CanonicalMetric = {
  name: string;
  description: string;
  unit: string;
  scopeNote: string;
};

export const CANONICAL_METRICS: Record<CanonicalMetricKey, CanonicalMetric> = {
  revenue: {
    name: 'Revenue',
    description: 'Top-line revenue recognized for the reporting period.',
    unit: 'currency',
    scopeNote: 'Income statement flow metric for period performance.',
  },
  gross_profit: {
    name: 'Gross Profit',
    description: 'Revenue minus cost of goods/services sold.',
    unit: 'currency',
    scopeNote: 'Income statement profitability before operating expenses.',
  },
  operating_income: {
    name: 'Operating Income',
    description: 'Profit from core operations before financing and taxes.',
    unit: 'currency',
    scopeNote: 'Income statement operating performance metric.',
  },
  net_income: {
    name: 'Net Income',
    description: 'Bottom-line earnings after all expenses, interest, and taxes.',
    unit: 'currency',
    scopeNote: 'Income statement final profit metric for the period.',
  },
  assets: {
    name: 'Assets',
    description: 'Total resources controlled by the entity at period end.',
    unit: 'currency',
    scopeNote: 'Balance sheet stock metric at a point in time.',
  },
  liabilities: {
    name: 'Liabilities',
    description: 'Total obligations owed by the entity at period end.',
    unit: 'currency',
    scopeNote: 'Balance sheet stock metric at a point in time.',
  },
  equity: {
    name: 'Equity',
    description: 'Residual interest in assets after deducting liabilities.',
    unit: 'currency',
    scopeNote: 'Balance sheet stock metric for owners\' claim.',
  },
  cfo: {
    name: 'Cash Flow from Operations (CFO)',
    description: 'Net cash generated by operating activities during the period.',
    unit: 'currency',
    scopeNote: 'Cash flow statement operating section metric.',
  },
  capex: {
    name: 'Capital Expenditures (Capex)',
    description: 'Cash spent on property, plant, equipment, and similar long-lived assets.',
    unit: 'currency',
    scopeNote: 'Cash flow investing outflow metric for reinvestment.',
  },
  fcf: {
    name: 'Free Cash Flow (FCF)',
    description: 'Operating cash flow minus capital expenditures.',
    unit: 'currency',
    scopeNote: 'Derived cash generation metric (CFO - Capex).',
  },
  shares: {
    name: 'Shares Outstanding',
    description: 'Weighted or period-end shares used for per-share analytics.',
    unit: 'shares',
    scopeNote: 'Capital structure quantity metric, not a currency amount.',
  },
};
